import groovy.json.JsonOutput 

node {

    def app

    stage('Clone repository') {
        /* Let's make sure we have the repository cloned to our workspace */

        checkout scm
    }

    stage('Build image') {
        /* This builds the actual image; synonymous to
         * docker build on the command line */

        app = docker.build("tadamhicks/demo_app")
    }

    stage('Test image') {
        /* Ideally, we would run a test framework against our image.
         * For this example, we're using a Volkswagen-type approach ;-) */

        app.inside {
            sh 'echo "Tests passed"'
        }
    }

    stage('Push image') {
        /* Finally, we'll push the image with two tags:
         * First, the incremental build number from Jenkins
         * Second, the 'latest' tag.
         * Pushing multiple tags is cheap, as all the layers are reused. */
        docker.withRegistry('https://registry.hub.docker.com', 'docker-hub-credentials') {
            app.push("${env.BUILD_NUMBER}")
            app.push("latest")
        }
    }

    stage('Provision Dev App') {
        /*
         *
         *  */

        withCredentials([string(credentialsId: 'demo-morph-scrt', variable: 'bearer')]) {
            String morpheusUrl = 'https://demo.morpheusdata.com/api/apps'

            Map<?, ?> postBody = [
  "id": 1,
  "templateName": "Spud Marketing",
  "defaultCluster": null,
  "defaultPool": null,
  "name": "jera demo",
  "group": [
    "id": 2,
    "name": "Demo"
  ],
  "tiers": [
    "Web": [
      "instances": [
        [
          "instance": [
            "cloud": "AWS",
            "type": "tomcat",
            "layout": [
              "code": "tomcat-amazon-7.0.62-single",
              "id": 616
            ]
          ],
          "config": [
            "publicIpType": "subnet",
            "resourcePoolId": 129
          ],
          "backup": [
            "backupRepository": 2,
            "createBackup": true,
            "jobAction": "new",
            "jobRetentionCount": "2",
            "enabled": true,
            "showScheduledBackupWarning": false,
            "providerBackupType": "null"
          ],
          "layout": [
            "id": 616,
            "code": "tomcat-amazon-7.0.62-single",
            "name": "Amazon Tomcat",
            "instanceVersion": "Tomcat 7 jdk 7",
            "description": "This will provision a single process with no redundancy",
            "sortOrder": 10,
            "hasSslCert": false,
            "provisionType": [
              "id": 11,
              "name": "Amazon",
              "description": null,
              "code": "amazon",
              "aclEnabled": false,
              "multiTenant": false,
              "managed": true,
              "hostNetwork": true,
              "customSupported": true,
              "mapPorts": false,
              "exportServer": false,
              "viewSet": "amazonCustom",
              "serverType": "ami",
              "hostType": "vm",
              "addVolumes": true,
              "hasVolumes": true,
              "hasDatastore": false,
              "hasNetworks": true,
              "maxNetworks": 0,
              "customizeVolume": true,
              "rootDiskCustomizable": true,
              "rootDiskSizeKnown": true,
              "rootDiskResizable": true,
              "lvmSupported": true,
              "hostDiskMode": "lvm",
              "minDisk": 1,
              "maxDisk": null,
              "resizeCopiesVolumes": true,
              "supportsAutoDatastore": false,
              "hasZonePools": true,
              "optionTypes": [
                [
                  "id": 518,
                  "name": "config.noAgent",
                  "code": "provisionType.general.noAgent",
                  "description": null,
                  "fieldName": "noAgent",
                  "fieldLabel": "Skip Agent Install",
                  "fieldContext": "config",
                  "fieldGroup": "Advanced Options",
                  "fieldClass": null,
                  "fieldAddOn": null,
                  "placeHolder": null,
                  "helpBlock": "Skipping Agent installation will result in a lack of logging and guest operating system statistics. Automation scripts may also be adversely affected.",
                  "defaultValue": null,
                  "optionSource": null,
                  "type": "checkbox",
                  "advanced": false,
                  "required": false,
                  "editable": false,
                  "config": [],
                  "displayOrder": 4,
                  "wrapperClass": null,
                  "enabled": true,
                  "noBlank": false,
                  "dependsOnCode": null,
                  "contextualDefault": null,
                  "value": null,
                  "label": "Skip Agent Install",
                  "formGroupClass": null,
                  "isCheckbox": true,
                  "isChecked": false,
                  "canLock": true,
                  "hidden": false,
                  "errorName": "noAgent"
                ],
                [
                  "id": 530,
                  "name": "config.availabilityId",
                  "code": "provisionType.amazon.availabilityId",
                  "description": null,
                  "fieldName": "availabilityId",
                  "fieldLabel": "Amazon Zone",
                  "fieldContext": "config",
                  "fieldGroup": "Options",
                  "fieldClass": null,
                  "fieldAddOn": null,
                  "placeHolder": null,
                  "helpBlock": "",
                  "defaultValue": null,
                  "optionSource": "amazonZones",
                  "type": "select",
                  "advanced": false,
                  "required": false,
                  "editable": false,
                  "config": [],
                  "displayOrder": 100,
                  "wrapperClass": null,
                  "enabled": true,
                  "noBlank": false,
                  "dependsOnCode": "provisionType.amazon.isEC2",
                  "contextualDefault": null,
                  "value": null,
                  "label": "Amazon Zone",
                  "formGroupClass": null,
                  "isSelect": true,
                  "isLoaded": false,
                  "canLock": true,
                  "hidden": true,
                  "dependsOnValue": "true",
                  "errorName": "availabilityId"
                ],
                [
                  "id": 977,
                  "name": "config.isEC2",
                  "code": "provisionType.amazon.isEC2",
                  "description": null,
                  "fieldName": "isEC2",
                  "fieldLabel": "Amazon Cloud Type",
                  "fieldContext": "config",
                  "fieldGroup": "Options",
                  "fieldClass": null,
                  "fieldAddOn": null,
                  "placeHolder": null,
                  "helpBlock": "",
                  "defaultValue": "false",
                  "optionSource": null,
                  "type": "hidden",
                  "advanced": false,
                  "required": false,
                  "editable": false,
                  "config": [],
                  "displayOrder": 100,
                  "wrapperClass": null,
                  "enabled": true,
                  "noBlank": false,
                  "dependsOnCode": null,
                  "contextualDefault": false,
                  "value": "false",
                  "label": "Amazon Cloud Type",
                  "formGroupClass": null,
                  "isHidden": true,
                  "hidden": true,
                  "canLock": true,
                  "errorName": "isEC2"
                ],
                [
                  "id": 62,
                  "name": "config.securityId",
                  "code": "provisionType.amazon.securityId",
                  "description": null,
                  "fieldName": "securityId",
                  "fieldLabel": "Security Group",
                  "fieldContext": "config",
                  "fieldGroup": "Options",
                  "fieldClass": null,
                  "fieldAddOn": null,
                  "placeHolder": null,
                  "helpBlock": "",
                  "defaultValue": null,
                  "optionSource": "amazonSecurityGroup",
                  "type": "select",
                  "advanced": false,
                  "required": true,
                  "editable": false,
                  "config": [],
                  "displayOrder": 102,
                  "wrapperClass": null,
                  "enabled": true,
                  "noBlank": null,
                  "dependsOnCode": null,
                  "contextualDefault": null,
                  "value": null,
                  "label": "Security Group",
                  "formGroupClass": null,
                  "isSelect": true,
                  "isLoaded": false,
                  "canLock": true,
                  "hidden": false
                ],
                [
                  "id": 531,
                  "name": "config.publicIpType",
                  "code": "provisionType.amazon.publicIpType",
                  "description": null,
                  "fieldName": "publicIpType",
                  "fieldLabel": "Public IP",
                  "fieldContext": "config",
                  "fieldGroup": "Options",
                  "fieldClass": null,
                  "fieldAddOn": null,
                  "placeHolder": null,
                  "helpBlock": "",
                  "defaultValue": "subnet",
                  "optionSource": "amazonPublicIpTypes",
                  "type": "select",
                  "advanced": false,
                  "required": false,
                  "editable": false,
                  "config": [],
                  "displayOrder": 103,
                  "wrapperClass": null,
                  "enabled": true,
                  "noBlank": true,
                  "dependsOnCode": null,
                  "contextualDefault": null,
                  "value": "subnet",
                  "label": "Public IP",
                  "formGroupClass": null,
                  "isSelect": true,
                  "isLoaded": false,
                  "canLock": true,
                  "hidden": false,
                  "errorName": "publicIpType"
                ],
                [
                  "id": 532,
                  "name": "config.instanceProfile",
                  "code": "provisionType.amazon.instanceProfile",
                  "description": null,
                  "fieldName": "instanceProfile",
                  "fieldLabel": "IAM Profile",
                  "fieldContext": "config",
                  "fieldGroup": "Advanced Options",
                  "fieldClass": null,
                  "fieldAddOn": null,
                  "placeHolder": null,
                  "helpBlock": "",
                  "defaultValue": null,
                  "optionSource": "amazonInstanceProfiles",
                  "type": "select",
                  "advanced": false,
                  "required": false,
                  "editable": false,
                  "config": [],
                  "displayOrder": 106,
                  "wrapperClass": null,
                  "enabled": true,
                  "noBlank": false,
                  "dependsOnCode": null,
                  "contextualDefault": null,
                  "value": null,
                  "label": "IAM Profile",
                  "formGroupClass": null,
                  "isSelect": true,
                  "isLoaded": false,
                  "canLock": true,
                  "hidden": false,
                  "errorName": "instanceProfile"
                ]
              ],
              "customOptionTypes": [
                [
                  "id": 777,
                  "name": "backup type",
                  "code": "provisionType.amazon.custom.instanceType.backupType",
                  "description": null,
                  "fieldName": "backupType",
                  "fieldLabel": "Backup Type",
                  "fieldContext": "instanceType",
                  "fieldGroup": "Amazon Options",
                  "fieldClass": null,
                  "fieldAddOn": null,
                  "placeHolder": null,
                  "helpBlock": "",
                  "defaultValue": "amazonSnapshot",
                  "optionSource": null,
                  "type": "hidden",
                  "advanced": false,
                  "required": false,
                  "editable": false,
                  "config": [],
                  "displayOrder": 4,
                  "wrapperClass": null,
                  "enabled": true,
                  "noBlank": false,
                  "dependsOnCode": null,
                  "contextualDefault": false
                ],
                [
                  "id": 779,
                  "name": "stat type code",
                  "code": "provisionType.amazon.custom.containerType.statTypeCode",
                  "description": null,
                  "fieldName": "statTypeCode",
                  "fieldLabel": "Stat Type Code",
                  "fieldContext": "containerType",
                  "fieldGroup": "Amazon Options",
                  "fieldClass": null,
                  "fieldAddOn": null,
                  "placeHolder": null,
                  "helpBlock": "",
                  "defaultValue": "amazon",
                  "optionSource": null,
                  "type": "hidden",
                  "advanced": false,
                  "required": false,
                  "editable": false,
                  "config": [],
                  "displayOrder": 6,
                  "wrapperClass": null,
                  "enabled": true,
                  "noBlank": false,
                  "dependsOnCode": null,
                  "contextualDefault": false
                ],
                [
                  "id": 781,
                  "name": "server type",
                  "code": "provisionType.amazon.custom.containerType.serverType",
                  "description": null,
                  "fieldName": "serverType",
                  "fieldLabel": "Server Type",
                  "fieldContext": "containerType",
                  "fieldGroup": "Amazon Options",
                  "fieldClass": null,
                  "fieldAddOn": null,
                  "placeHolder": null,
                  "helpBlock": "",
                  "defaultValue": "vm",
                  "optionSource": null,
                  "type": "hidden",
                  "advanced": false,
                  "required": false,
                  "editable": false,
                  "config": [],
                  "displayOrder": 8,
                  "wrapperClass": null,
                  "enabled": true,
                  "noBlank": false,
                  "dependsOnCode": null,
                  "contextualDefault": false
                ],
                [
                  "id": 778,
                  "name": "backup type",
                  "code": "provisionType.amazon.custom.instanceType.viewSet",
                  "description": null,
                  "fieldName": "viewSet",
                  "fieldLabel": "View Set",
                  "fieldContext": "instanceType",
                  "fieldGroup": "Amazon Options",
                  "fieldClass": null,
                  "fieldAddOn": null,
                  "placeHolder": null,
                  "helpBlock": "",
                  "defaultValue": "amazonCustom",
                  "optionSource": null,
                  "type": "hidden",
                  "advanced": false,
                  "required": false,
                  "editable": false,
                  "config": [],
                  "displayOrder": 5,
                  "wrapperClass": null,
                  "enabled": true,
                  "noBlank": false,
                  "dependsOnCode": null,
                  "contextualDefault": false
                ],
                [
                  "id": 774,
                  "name": "virtual image",
                  "code": "provisionType.amazon.custom.containerType.virtualImageId",
                  "description": null,
                  "fieldName": "virtualImageId",
                  "fieldLabel": "AMI Image",
                  "fieldContext": "containerType",
                  "fieldGroup": "Amazon Options",
                  "fieldClass": null,
                  "fieldAddOn": null,
                  "placeHolder": null,
                  "helpBlock": "",
                  "defaultValue": null,
                  "optionSource": "amazonAccountImage",
                  "type": "select",
                  "advanced": false,
                  "required": true,
                  "editable": false,
                  "config": [],
                  "displayOrder": 1,
                  "wrapperClass": null,
                  "enabled": true,
                  "noBlank": false,
                  "dependsOnCode": null,
                  "contextualDefault": false
                ],
                [
                  "id": 780,
                  "name": "log type code",
                  "code": "provisionType.amazon.custom.containerType.logTypeCode",
                  "description": null,
                  "fieldName": "logTypeCode",
                  "fieldLabel": "Log Type Code",
                  "fieldContext": "containerType",
                  "fieldGroup": "Amazon Options",
                  "fieldClass": null,
                  "fieldAddOn": null,
                  "placeHolder": null,
                  "helpBlock": "",
                  "defaultValue": "amazon",
                  "optionSource": null,
                  "type": "hidden",
                  "advanced": false,
                  "required": false,
                  "editable": false,
                  "config": [],
                  "displayOrder": 7,
                  "wrapperClass": null,
                  "enabled": true,
                  "noBlank": false,
                  "dependsOnCode": null,
                  "contextualDefault": false
                ],
                [
                  "id": 782,
                  "name": "layout description",
                  "code": "provisionType.amazon.custom.instanceTypeLayout.description",
                  "description": null,
                  "fieldName": "description",
                  "fieldLabel": "Layout Description",
                  "fieldContext": "instanceTypeLayout",
                  "fieldGroup": "Amazon Options",
                  "fieldClass": null,
                  "fieldAddOn": null,
                  "placeHolder": null,
                  "helpBlock": "",
                  "defaultValue": "This will provision a single vm",
                  "optionSource": null,
                  "type": "hidden",
                  "advanced": false,
                  "required": false,
                  "editable": false,
                  "config": [],
                  "displayOrder": 9,
                  "wrapperClass": null,
                  "enabled": true,
                  "noBlank": false,
                  "dependsOnCode": null,
                  "contextualDefault": false
                ],
                [
                  "id": 775,
                  "name": "mount logs",
                  "code": "provisionType.amazon.custom.containerType.mountLogs",
                  "description": null,
                  "fieldName": "mountLogs",
                  "fieldLabel": "Log Folder",
                  "fieldContext": "containerType",
                  "fieldGroup": "Amazon Options",
                  "fieldClass": null,
                  "fieldAddOn": null,
                  "placeHolder": null,
                  "helpBlock": "",
                  "defaultValue": null,
                  "optionSource": null,
                  "type": "text",
                  "advanced": false,
                  "required": false,
                  "editable": false,
                  "config": [],
                  "displayOrder": 2,
                  "wrapperClass": null,
                  "enabled": true,
                  "noBlank": false,
                  "dependsOnCode": null,
                  "contextualDefault": false
                ],
                [
                  "id": 776,
                  "name": "mount data",
                  "code": "provisionType.amazon.custom.containerType.mountData",
                  "description": null,
                  "fieldName": "mountData",
                  "fieldLabel": "Deploy Folder",
                  "fieldContext": "containerType",
                  "fieldGroup": "Amazon Options",
                  "fieldClass": null,
                  "fieldAddOn": null,
                  "placeHolder": null,
                  "helpBlock": "(Optional) If using deployment services, this mount point will be replaced with the contents of said deployments.",
                  "defaultValue": null,
                  "optionSource": null,
                  "type": "text",
                  "advanced": false,
                  "required": false,
                  "editable": false,
                  "config": [],
                  "displayOrder": 3,
                  "wrapperClass": null,
                  "enabled": true,
                  "noBlank": false,
                  "dependsOnCode": null,
                  "contextualDefault": false
                ]
              ],
              "networkTypes": [],
              "storageTypes": [
                [
                  "id": 6,
                  "code": "amazon-gp2",
                  "name": "gp2",
                  "displayOrder": 1,
                  "defaultType": true,
                  "customLabel": true,
                  "customSize": true,
                  "customSizeOptions": null
                ],
                [
                  "id": 8,
                  "code": "amazon-sc1",
                  "name": "sc1",
                  "displayOrder": 4,
                  "defaultType": false,
                  "customLabel": true,
                  "customSize": true,
                  "customSizeOptions": null
                ],
                [
                  "id": 5,
                  "code": "amazon-io1",
                  "name": "io1",
                  "displayOrder": 2,
                  "defaultType": false,
                  "customLabel": true,
                  "customSize": true,
                  "customSizeOptions": null
                ],
                [
                  "id": 7,
                  "code": "amazon-st1",
                  "name": "st1",
                  "displayOrder": 3,
                  "defaultType": false,
                  "customLabel": true,
                  "customSize": true,
                  "customSizeOptions": null
                ]
              ],
              "rootStorageTypes": [
                [
                  "id": 6,
                  "code": "amazon-gp2",
                  "name": "gp2",
                  "displayOrder": 1,
                  "defaultType": true,
                  "customLabel": true,
                  "customSize": true,
                  "customSizeOptions": null
                ],
                [
                  "id": 5,
                  "code": "amazon-io1",
                  "name": "io1",
                  "displayOrder": 2,
                  "defaultType": false,
                  "customLabel": true,
                  "customSize": true,
                  "customSizeOptions": null
                ]
              ],
              "controllerTypes": []
            ],
            "containerTypeSet": [
              "id": 661,
              "containerType": [
                "id": 587,
                "virtualImageId": 374
              ]
            ],
            "mounts": [],
            "ports": [
              [
                "id": 13,
                "code": "tomcat.8080",
                "name": "Http",
                "shortName": "http",
                "internalPort": 8080,
                "externalPort": 8080,
                "loadBalancePort": 80,
                "sortOrder": 0,
                "loadBalanceProtocol": "http",
                "loadBalance": true,
                "visible": true
              ]
            ],
            "optionTypes": [],
            "deploymentOptionTypes": [
              [
                "id": 489,
                "name": "Catalina Opts",
                "code": "containerDeployType.tomcat.catalinaOpts",
                "description": null,
                "fieldName": "catalinaOpts",
                "fieldLabel": "CATALINA_OPTS",
                "fieldContext": "appDeploy.configMap",
                "fieldGroup": "Config",
                "fieldClass": null,
                "fieldAddOn": null,
                "placeHolder": null,
                "helpBlock": "",
                "defaultValue": null,
                "optionSource": null,
                "type": "text",
                "advanced": false,
                "required": false,
                "editable": false,
                "config": [],
                "displayOrder": 0,
                "wrapperClass": null,
                "enabled": true,
                "noBlank": null,
                "dependsOnCode": null,
                "contextualDefault": null
              ]
            ],
            "loadBalancerPorts": [
              [
                "internalPort": 8080,
                "externalPort": 8080,
                "loadBalancePort": 80,
                "loadBalanceProtocol": "http"
              ]
            ],
            "selected": true
          ],
          "loadBalancer": [
            [
              "externalAddressCheck": false,
              "protocol": "http",
              "vipPort": 80,
              "internalPort": 8080,
              "vipHostname": "spudmarketing.com",
              "vipShared": "off",
              "name": "spudmarketing",
              "externalAddress": "off",
              "id": -2,
              "balanceMode": "leastconnections",
              "externalPort": 8080
            ]
          ],
          "ports": [
            [
              "code": "tomcat.8080",
              "visible": true,
              "internalPort": 8080,
              "loadBalancePort": 80,
              "loadBalanceProtocol": "http",
              "sortOrder": 0,
              "name": "Http",
              "id": 13,
              "shortName": "http",
              "externalPort": 8080,
              "loadBalance": true
            ]
          ],
          "networkInterfaces": [
            [
              "primaryInterface": true,
              "showNetworkPoolLabel": true,
              "showNetworkDhcpLabel": false,
              "network": [
                "idName": "Labs Public AWS",
                "id": "networkGroup-1",
                "hasPool": ""
              ]
            ]
          ],
          "volumes": [
            [
              "vId": 374,
              "volumeCustomizable": true,
              "readonlyName": true,
              "size": 20,
              "maxIOPS": null,
              "name": "root",
              "rootVolume": true,
              "storageType": 6,
              "maxStorage": 0
            ]
          ]
        ]
      ],
      "tierIndex": 0
    ],
    "Database": [
      "instances": [
        [
          "instance": [
            "cloud": "AWS",
            "type": "mysql",
            "layout": [
              "code": "mysql-amazon-5.6-single",
              "id": 439
            ]
          ],
          "config": [
            "publicIpType": "subnet",
            "resourcePoolId": 129
          ],
          "backup": [
            "backupRepository": 1,
            "createBackup": true,
            "jobAction": "new",
            "jobRetentionCount": "2",
            "enabled": true,
            "showScheduledBackupWarning": false,
            "providerBackupType": -1
          ],
          "layout": [
            "id": 439,
            "code": "mysql-amazon-5.6-single",
            "name": "Amazon Master",
            "instanceVersion": "5.6",
            "description": "This will provision a single master vm in amazon",
            "sortOrder": 30,
            "hasSslCert": false,
            "provisionType": [
              "id": 11,
              "name": "Amazon",
              "description": null,
              "code": "amazon",
              "aclEnabled": false,
              "multiTenant": false,
              "managed": true,
              "hostNetwork": true,
              "customSupported": true,
              "mapPorts": false,
              "exportServer": false,
              "viewSet": "amazonCustom",
              "serverType": "ami",
              "hostType": "vm",
              "addVolumes": true,
              "hasVolumes": true,
              "hasDatastore": false,
              "hasNetworks": true,
              "maxNetworks": 0,
              "customizeVolume": true,
              "rootDiskCustomizable": true,
              "rootDiskSizeKnown": true,
              "rootDiskResizable": true,
              "lvmSupported": true,
              "hostDiskMode": "lvm",
              "minDisk": 1,
              "maxDisk": null,
              "resizeCopiesVolumes": true,
              "supportsAutoDatastore": false,
              "hasZonePools": true,
              "optionTypes": [
                [
                  "id": 518,
                  "name": "config.noAgent",
                  "code": "provisionType.general.noAgent",
                  "description": null,
                  "fieldName": "noAgent",
                  "fieldLabel": "Skip Agent Install",
                  "fieldContext": "config",
                  "fieldGroup": "Advanced Options",
                  "fieldClass": null,
                  "fieldAddOn": null,
                  "placeHolder": null,
                  "helpBlock": "Skipping Agent installation will result in a lack of logging and guest operating system statistics. Automation scripts may also be adversely affected.",
                  "defaultValue": null,
                  "optionSource": null,
                  "type": "checkbox",
                  "advanced": false,
                  "required": false,
                  "editable": false,
                  "config": [],
                  "displayOrder": 4,
                  "wrapperClass": null,
                  "enabled": true,
                  "noBlank": false,
                  "dependsOnCode": null,
                  "contextualDefault": null,
                  "value": null,
                  "label": "Skip Agent Install",
                  "formGroupClass": null,
                  "isCheckbox": true,
                  "isChecked": false,
                  "canLock": true,
                  "hidden": false,
                  "errorName": "noAgent"
                ],
                [
                  "id": 530,
                  "name": "config.availabilityId",
                  "code": "provisionType.amazon.availabilityId",
                  "description": null,
                  "fieldName": "availabilityId",
                  "fieldLabel": "Amazon Zone",
                  "fieldContext": "config",
                  "fieldGroup": "Options",
                  "fieldClass": null,
                  "fieldAddOn": null,
                  "placeHolder": null,
                  "helpBlock": "",
                  "defaultValue": null,
                  "optionSource": "amazonZones",
                  "type": "select",
                  "advanced": false,
                  "required": false,
                  "editable": false,
                  "config": [],
                  "displayOrder": 100,
                  "wrapperClass": null,
                  "enabled": true,
                  "noBlank": false,
                  "dependsOnCode": "provisionType.amazon.isEC2",
                  "contextualDefault": null,
                  "value": null,
                  "label": "Amazon Zone",
                  "formGroupClass": null,
                  "isSelect": true,
                  "isLoaded": false,
                  "canLock": true,
                  "hidden": true,
                  "dependsOnValue": "true",
                  "errorName": "availabilityId"
                ],
                [
                  "id": 977,
                  "name": "config.isEC2",
                  "code": "provisionType.amazon.isEC2",
                  "description": null,
                  "fieldName": "isEC2",
                  "fieldLabel": "Amazon Cloud Type",
                  "fieldContext": "config",
                  "fieldGroup": "Options",
                  "fieldClass": null,
                  "fieldAddOn": null,
                  "placeHolder": null,
                  "helpBlock": "",
                  "defaultValue": "false",
                  "optionSource": null,
                  "type": "hidden",
                  "advanced": false,
                  "required": false,
                  "editable": false,
                  "config": [],
                  "displayOrder": 100,
                  "wrapperClass": null,
                  "enabled": true,
                  "noBlank": false,
                  "dependsOnCode": null,
                  "contextualDefault": false,
                  "value": "false",
                  "label": "Amazon Cloud Type",
                  "formGroupClass": null,
                  "isHidden": true,
                  "hidden": true,
                  "canLock": true,
                  "errorName": "isEC2"
                ],
                [
                  "id": 62,
                  "name": "config.securityId",
                  "code": "provisionType.amazon.securityId",
                  "description": null,
                  "fieldName": "securityId",
                  "fieldLabel": "Security Group",
                  "fieldContext": "config",
                  "fieldGroup": "Options",
                  "fieldClass": null,
                  "fieldAddOn": null,
                  "placeHolder": null,
                  "helpBlock": "",
                  "defaultValue": null,
                  "optionSource": "amazonSecurityGroup",
                  "type": "select",
                  "advanced": false,
                  "required": true,
                  "editable": false,
                  "config": [],
                  "displayOrder": 102,
                  "wrapperClass": null,
                  "enabled": true,
                  "noBlank": null,
                  "dependsOnCode": null,
                  "contextualDefault": null,
                  "value": null,
                  "label": "Security Group",
                  "formGroupClass": null,
                  "isSelect": true,
                  "isLoaded": false,
                  "canLock": true,
                  "hidden": false
                ],
                [
                  "id": 531,
                  "name": "config.publicIpType",
                  "code": "provisionType.amazon.publicIpType",
                  "description": null,
                  "fieldName": "publicIpType",
                  "fieldLabel": "Public IP",
                  "fieldContext": "config",
                  "fieldGroup": "Options",
                  "fieldClass": null,
                  "fieldAddOn": null,
                  "placeHolder": null,
                  "helpBlock": "",
                  "defaultValue": "subnet",
                  "optionSource": "amazonPublicIpTypes",
                  "type": "select",
                  "advanced": false,
                  "required": false,
                  "editable": false,
                  "config": [],
                  "displayOrder": 103,
                  "wrapperClass": null,
                  "enabled": true,
                  "noBlank": true,
                  "dependsOnCode": null,
                  "contextualDefault": null,
                  "value": "subnet",
                  "label": "Public IP",
                  "formGroupClass": null,
                  "isSelect": true,
                  "isLoaded": false,
                  "canLock": true,
                  "hidden": false,
                  "errorName": "publicIpType"
                ],
                [
                  "id": 532,
                  "name": "config.instanceProfile",
                  "code": "provisionType.amazon.instanceProfile",
                  "description": null,
                  "fieldName": "instanceProfile",
                  "fieldLabel": "IAM Profile",
                  "fieldContext": "config",
                  "fieldGroup": "Advanced Options",
                  "fieldClass": null,
                  "fieldAddOn": null,
                  "placeHolder": null,
                  "helpBlock": "",
                  "defaultValue": null,
                  "optionSource": "amazonInstanceProfiles",
                  "type": "select",
                  "advanced": false,
                  "required": false,
                  "editable": false,
                  "config": [],
                  "displayOrder": 106,
                  "wrapperClass": null,
                  "enabled": true,
                  "noBlank": false,
                  "dependsOnCode": null,
                  "contextualDefault": null,
                  "value": null,
                  "label": "IAM Profile",
                  "formGroupClass": null,
                  "isSelect": true,
                  "isLoaded": false,
                  "canLock": true,
                  "hidden": false,
                  "errorName": "instanceProfile"
                ]
              ],
              "customOptionTypes": [
                [
                  "id": 782,
                  "name": "layout description",
                  "code": "provisionType.amazon.custom.instanceTypeLayout.description",
                  "description": null,
                  "fieldName": "description",
                  "fieldLabel": "Layout Description",
                  "fieldContext": "instanceTypeLayout",
                  "fieldGroup": "Amazon Options",
                  "fieldClass": null,
                  "fieldAddOn": null,
                  "placeHolder": null,
                  "helpBlock": "",
                  "defaultValue": "This will provision a single vm",
                  "optionSource": null,
                  "type": "hidden",
                  "advanced": false,
                  "required": false,
                  "editable": false,
                  "config": [],
                  "displayOrder": 9,
                  "wrapperClass": null,
                  "enabled": true,
                  "noBlank": false,
                  "dependsOnCode": null,
                  "contextualDefault": false
                ],
                [
                  "id": 778,
                  "name": "backup type",
                  "code": "provisionType.amazon.custom.instanceType.viewSet",
                  "description": null,
                  "fieldName": "viewSet",
                  "fieldLabel": "View Set",
                  "fieldContext": "instanceType",
                  "fieldGroup": "Amazon Options",
                  "fieldClass": null,
                  "fieldAddOn": null,
                  "placeHolder": null,
                  "helpBlock": "",
                  "defaultValue": "amazonCustom",
                  "optionSource": null,
                  "type": "hidden",
                  "advanced": false,
                  "required": false,
                  "editable": false,
                  "config": [],
                  "displayOrder": 5,
                  "wrapperClass": null,
                  "enabled": true,
                  "noBlank": false,
                  "dependsOnCode": null,
                  "contextualDefault": false
                ],
                [
                  "id": 776,
                  "name": "mount data",
                  "code": "provisionType.amazon.custom.containerType.mountData",
                  "description": null,
                  "fieldName": "mountData",
                  "fieldLabel": "Deploy Folder",
                  "fieldContext": "containerType",
                  "fieldGroup": "Amazon Options",
                  "fieldClass": null,
                  "fieldAddOn": null,
                  "placeHolder": null,
                  "helpBlock": "(Optional) If using deployment services, this mount point will be replaced with the contents of said deployments.",
                  "defaultValue": null,
                  "optionSource": null,
                  "type": "text",
                  "advanced": false,
                  "required": false,
                  "editable": false,
                  "config": [],
                  "displayOrder": 3,
                  "wrapperClass": null,
                  "enabled": true,
                  "noBlank": false,
                  "dependsOnCode": null,
                  "contextualDefault": false
                ],
                [
                  "id": 775,
                  "name": "mount logs",
                  "code": "provisionType.amazon.custom.containerType.mountLogs",
                  "description": null,
                  "fieldName": "mountLogs",
                  "fieldLabel": "Log Folder",
                  "fieldContext": "containerType",
                  "fieldGroup": "Amazon Options",
                  "fieldClass": null,
                  "fieldAddOn": null,
                  "placeHolder": null,
                  "helpBlock": "",
                  "defaultValue": null,
                  "optionSource": null,
                  "type": "text",
                  "advanced": false,
                  "required": false,
                  "editable": false,
                  "config": [],
                  "displayOrder": 2,
                  "wrapperClass": null,
                  "enabled": true,
                  "noBlank": false,
                  "dependsOnCode": null,
                  "contextualDefault": false
                ],
                [
                  "id": 779,
                  "name": "stat type code",
                  "code": "provisionType.amazon.custom.containerType.statTypeCode",
                  "description": null,
                  "fieldName": "statTypeCode",
                  "fieldLabel": "Stat Type Code",
                  "fieldContext": "containerType",
                  "fieldGroup": "Amazon Options",
                  "fieldClass": null,
                  "fieldAddOn": null,
                  "placeHolder": null,
                  "helpBlock": "",
                  "defaultValue": "amazon",
                  "optionSource": null,
                  "type": "hidden",
                  "advanced": false,
                  "required": false,
                  "editable": false,
                  "config": [],
                  "displayOrder": 6,
                  "wrapperClass": null,
                  "enabled": true,
                  "noBlank": false,
                  "dependsOnCode": null,
                  "contextualDefault": false
                ],
                [
                  "id": 781,
                  "name": "server type",
                  "code": "provisionType.amazon.custom.containerType.serverType",
                  "description": null,
                  "fieldName": "serverType",
                  "fieldLabel": "Server Type",
                  "fieldContext": "containerType",
                  "fieldGroup": "Amazon Options",
                  "fieldClass": null,
                  "fieldAddOn": null,
                  "placeHolder": null,
                  "helpBlock": "",
                  "defaultValue": "vm",
                  "optionSource": null,
                  "type": "hidden",
                  "advanced": false,
                  "required": false,
                  "editable": false,
                  "config": [],
                  "displayOrder": 8,
                  "wrapperClass": null,
                  "enabled": true,
                  "noBlank": false,
                  "dependsOnCode": null,
                  "contextualDefault": false
                ],
                [
                  "id": 777,
                  "name": "backup type",
                  "code": "provisionType.amazon.custom.instanceType.backupType",
                  "description": null,
                  "fieldName": "backupType",
                  "fieldLabel": "Backup Type",
                  "fieldContext": "instanceType",
                  "fieldGroup": "Amazon Options",
                  "fieldClass": null,
                  "fieldAddOn": null,
                  "placeHolder": null,
                  "helpBlock": "",
                  "defaultValue": "amazonSnapshot",
                  "optionSource": null,
                  "type": "hidden",
                  "advanced": false,
                  "required": false,
                  "editable": false,
                  "config": [],
                  "displayOrder": 4,
                  "wrapperClass": null,
                  "enabled": true,
                  "noBlank": false,
                  "dependsOnCode": null,
                  "contextualDefault": false
                ],
                [
                  "id": 774,
                  "name": "virtual image",
                  "code": "provisionType.amazon.custom.containerType.virtualImageId",
                  "description": null,
                  "fieldName": "virtualImageId",
                  "fieldLabel": "AMI Image",
                  "fieldContext": "containerType",
                  "fieldGroup": "Amazon Options",
                  "fieldClass": null,
                  "fieldAddOn": null,
                  "placeHolder": null,
                  "helpBlock": "",
                  "defaultValue": null,
                  "optionSource": "amazonAccountImage",
                  "type": "select",
                  "advanced": false,
                  "required": true,
                  "editable": false,
                  "config": [],
                  "displayOrder": 1,
                  "wrapperClass": null,
                  "enabled": true,
                  "noBlank": false,
                  "dependsOnCode": null,
                  "contextualDefault": false
                ],
                [
                  "id": 780,
                  "name": "log type code",
                  "code": "provisionType.amazon.custom.containerType.logTypeCode",
                  "description": null,
                  "fieldName": "logTypeCode",
                  "fieldLabel": "Log Type Code",
                  "fieldContext": "containerType",
                  "fieldGroup": "Amazon Options",
                  "fieldClass": null,
                  "fieldAddOn": null,
                  "placeHolder": null,
                  "helpBlock": "",
                  "defaultValue": "amazon",
                  "optionSource": null,
                  "type": "hidden",
                  "advanced": false,
                  "required": false,
                  "editable": false,
                  "config": [],
                  "displayOrder": 7,
                  "wrapperClass": null,
                  "enabled": true,
                  "noBlank": false,
                  "dependsOnCode": null,
                  "contextualDefault": false
                ]
              ],
              "networkTypes": [],
              "storageTypes": [
                [
                  "id": 6,
                  "code": "amazon-gp2",
                  "name": "gp2",
                  "displayOrder": 1,
                  "defaultType": true,
                  "customLabel": true,
                  "customSize": true,
                  "customSizeOptions": null
                ],
                [
                  "id": 8,
                  "code": "amazon-sc1",
                  "name": "sc1",
                  "displayOrder": 4,
                  "defaultType": false,
                  "customLabel": true,
                  "customSize": true,
                  "customSizeOptions": null
                ],
                [
                  "id": 5,
                  "code": "amazon-io1",
                  "name": "io1",
                  "displayOrder": 2,
                  "defaultType": false,
                  "customLabel": true,
                  "customSize": true,
                  "customSizeOptions": null
                ],
                [
                  "id": 7,
                  "code": "amazon-st1",
                  "name": "st1",
                  "displayOrder": 3,
                  "defaultType": false,
                  "customLabel": true,
                  "customSize": true,
                  "customSizeOptions": null
                ]
              ],
              "rootStorageTypes": [
                [
                  "id": 6,
                  "code": "amazon-gp2",
                  "name": "gp2",
                  "displayOrder": 1,
                  "defaultType": true,
                  "customLabel": true,
                  "customSize": true,
                  "customSizeOptions": null
                ],
                [
                  "id": 5,
                  "code": "amazon-io1",
                  "name": "io1",
                  "displayOrder": 2,
                  "defaultType": false,
                  "customLabel": true,
                  "customSize": true,
                  "customSizeOptions": null
                ]
              ],
              "controllerTypes": []
            ],
            "containerTypeSet": [
              "id": 471,
              "containerType": [
                "id": 406,
                "virtualImageId": 508413
              ]
            ],
            "mounts": [
              [
                "id": 13,
                "code": "mysql-data",
                "name": "mysql data",
                "shortName": "data",
                "mountType": "volume",
                "sortOrder": 3,
                "required": false,
                "visible": true,
                "deployable": false,
                "canPersist": true
              ],
              [
                "id": 14,
                "code": "mysql-seed",
                "name": "mysql seed",
                "shortName": "seed",
                "mountType": "volume",
                "sortOrder": 2,
                "required": false,
                "visible": true,
                "deployable": true,
                "canPersist": false
              ],
              [
                "id": 15,
                "code": "mysql-logs",
                "name": "mysql logs",
                "shortName": "logs",
                "mountType": "volume",
                "sortOrder": 3,
                "required": false,
                "visible": true,
                "deployable": false,
                "canPersist": false
              ],
              [
                "id": 12,
                "code": "mysql-config",
                "name": "mysql config",
                "shortName": "config",
                "mountType": "config",
                "sortOrder": 0,
                "required": false,
                "visible": true,
                "deployable": false,
                "canPersist": false
              ]
            ],
            "ports": [
              [
                "id": 12,
                "code": "mysql.3306",
                "name": "Db Port",
                "shortName": "tcp",
                "internalPort": 3306,
                "externalPort": 3306,
                "loadBalancePort": null,
                "sortOrder": 0,
                "loadBalanceProtocol": null,
                "loadBalance": false,
                "visible": true
              ]
            ],
            "optionTypes": [
              [
                "id": 123,
                "name": "config.rootPassword",
                "code": "instanceType.mysql.rootPassword",
                "description": "An initial root password to be set on the mysql instance when provisioned.",
                "fieldName": "rootPassword",
                "fieldLabel": "Root Password",
                "fieldContext": "config",
                "fieldGroup": "Options",
                "fieldClass": null,
                "fieldAddOn": null,
                "placeHolder": "root password",
                "helpBlock": "",
                "defaultValue": null,
                "optionSource": null,
                "type": "password",
                "advanced": false,
                "required": true,
                "editable": false,
                "config": [],
                "displayOrder": 5,
                "wrapperClass": null,
                "enabled": true,
                "noBlank": null,
                "dependsOnCode": null,
                "contextualDefault": null,
                "value": "************",
                "label": "Root Password",
                "formGroupClass": null,
                "isPassword": true,
                "canLock": true,
                "hidden": false,
                "errorName": "rootPassword"
              ],
              [
                "id": 124,
                "name": "config.username",
                "code": "instanceType.mysql.username",
                "description": "Username of user to be automatically created in mysql.",
                "fieldName": "username",
                "fieldLabel": "Username",
                "fieldContext": "config",
                "fieldGroup": "Options",
                "fieldClass": null,
                "fieldAddOn": null,
                "placeHolder": "Create a MySQL admin user",
                "helpBlock": "",
                "defaultValue": null,
                "optionSource": null,
                "type": "text",
                "advanced": false,
                "required": true,
                "editable": false,
                "config": [],
                "displayOrder": 6,
                "wrapperClass": null,
                "enabled": true,
                "noBlank": null,
                "dependsOnCode": null,
                "contextualDefault": null,
                "value": "morpheus",
                "label": "Username",
                "formGroupClass": null,
                "isText": true,
                "canLock": true,
                "hidden": false,
                "errorName": "username"
              ],
              [
                "id": 125,
                "name": "config.password",
                "code": "instanceType.mysql.password",
                "description": "Password to be set for newly created user.",
                "fieldName": "password",
                "fieldLabel": "Password",
                "fieldContext": "config",
                "fieldGroup": "Options",
                "fieldClass": null,
                "fieldAddOn": null,
                "placeHolder": "admin user password",
                "helpBlock": "",
                "defaultValue": null,
                "optionSource": null,
                "type": "password",
                "advanced": false,
                "required": true,
                "editable": false,
                "config": [],
                "displayOrder": 7,
                "wrapperClass": null,
                "enabled": true,
                "noBlank": null,
                "dependsOnCode": null,
                "contextualDefault": null,
                "value": "************",
                "label": "Password",
                "formGroupClass": null,
                "isPassword": true,
                "canLock": true,
                "hidden": false,
                "errorName": "password"
              ]
            ],
            "deploymentOptionTypes": [],
            "loadBalancerPorts": [],
            "selected": true
          ],
          "loadBalancer": [],
          "ports": [
            [
              "code": "mysql.3306",
              "visible": true,
              "internalPort": 3306,
              "loadBalancePort": null,
              "loadBalanceProtocol": null,
              "sortOrder": 0,
              "name": "Db Port",
              "id": 12,
              "shortName": "tcp",
              "externalPort": 3306,
              "loadBalance": false
            ]
          ],
          "networkInterfaces": [
            [
              "primaryInterface": true,
              "showNetworkPoolLabel": true,
              "showNetworkDhcpLabel": false,
              "network": [
                "idName": "Labs Public AWS",
                "id": "networkGroup-1",
                "hasPool": ""
              ]
            ]
          ],
          "volumes": [
            [
              "vId": 508413,
              "volumeCustomizable": true,
              "readonlyName": false,
              "size": 15,
              "maxIOPS": null,
              "name": "root",
              "rootVolume": true,
              "storageType": 6,
              "maxStorage": 0
            ]
          ]
        ]
      ],
      "tierIndex": 1
    ]
  ],
  "config": [
    "isEC2": false,
    "isVpcSelectable": false
  ]
]


            echo morpheusApp.buildApp(morpheusUrl, postBody, "${bearer}")
        }
    }


}